name: Workflow à réutilisé
on:
  # Définir ce workflow comme réutilisable par d'autres workflows
  workflow_call:
    outputs:
      # Définir les sorties utilisables dans un autre workflow
      variable1:
        description: Premier output
        value: ${{ steps.etape1.outputs.VAR1 }} # On va chercher notre variable 1 depuis le fichier de sortie de notre étape.
      variable2:
        description: Second output
        value: ${{ steps.etape2.outputs.VAR2 }}
  workflow_dispatch:
jobs:
  job1:
    name: Génère des paramètres de sortie
    runs-on: ubuntu-latest
    steps:
      - name: set VAR1
        id: etape1
        run: echo "VAR1=Hello" >> $GITHUB_OUTPUT
      - name: set VAR2
        id: etape2
        run: echo "VAR2=World" >> $GITHUB_OUTPUT
      - name: echo VAR1 VAR2
        run: echo ${{ steps.etape1.outputs.VAR1 }} ${{ steps.etape2.outputs.VAR2 }}
  job2:
    name: Récupère les paramètres de job1 dans job2
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: echo sortie1 sortie2
        run: echo ${{ needs.job1.outputs.VAR1 }} ${{ needs.job1.outputs.VAR2 }}
