name: Workflow qui se déclenche lors de la création d'une issue
on:
  issues:
    types: opened

jobs:
  commentaire:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - run: gh issue comment $ISSUE_URL --body "Merci d'avoir ouvert cette issue !"
        env:
          # Récupération de notre token pour s'authentifier
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
  title:
    runs-on: ubuntu-latest
    steps:
      - name: Avec une variable d'environement
        env:
          TITRE: ${{ github.event.issue.title }}
        run: |
          echo "Nouvelle issue - $TITRE"
          echo "Utilisation d'une variable d'environnement intermédiaire pour atténuer le risque d'injection de code"
