name: Workflow lors d'un push
# Le workflow va se déclencher à chaque push de mon application
on:
  push:
    branches:
      - main
      - dev
jobs:
  upload:
    name: Build test et run application
    runs-on: ubuntu-latest
    steps:
      - name: Récupération de notre application
        uses: actions/checkout@v4
      - name: cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-package-${{ hashFiles('**/package-lock.json') }}
      - name: installation des dépendance
        run: npm ci
      - name: build de l'application
        run: npm run build
      - name: test
        run: npm run test
        continue-on-error: false # Le job échouera si les tests échouent
      - name: Upload du build # Exécute l'upload uniquement si les tests ont réussi
        if: ${{ success() && github.ref == 'refs/heads/main' }}
        uses: actions/upload-artifact@v4
        with:
          name: mon_app
          path: dist
  download:
    runs-on: ubuntu-latest
    needs: upload
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Récupérer l'artéfact
        uses: actions/download-artifact@v4
        with:
          name: mon_app
      - name: lister les fichiers
        run: ls

  docker:
    runs-on: ubuntu-latest
    needs: download
    if: ${{ github.ref == 'refs/heads/main' }}
    env:
      USERNAME: ${{ secrets.DOCKER_USERNAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker build -t $USERNAME/my_node_app

      - name: Push docker image
        run: docker push $USERNAME/my_node_app
