name: Workflow lors d'un push
# Le workflow va se déclencher à chaque push de mon application
on: push
jobs:
  upload:
    name: Build test et run application
    runs-on: ubuntu-latest
    steps:
      - name: Récupération de notre application
        uses: actions/checkout@v4
      - name: installation des dépendance
        run: npm ci
      - name: build de l'application
        run: npm run build
      - name: test
        run: npm run test
      - name: Upload du build
        uses: actions/upload-artifact@v4
        with:
          name: mon_app
          path: dist
  download:
    runs-on: ubuntu-latest
    needs: upload
    steps:
      - name: Récupérer l'artéfact
        uses: actions/download-artifact@v4
        with:
          name: mon_app
      - name: lister les fichiers
        run: ls
